module.exports = {
  apps: [
    {
      name: 'lyra-https',
      script: 'scripts/https-server.mjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '700M',
      node_args: '--max-old-space-size=700',
      env: {
        NODE_ENV: 'production',
        PORT: 443,
        NODE_OPTIONS: '--max-old-space-size=700',
      },
      error_file: './logs/https-error.log',
      out_file: './logs/https-out.log',
      log_file: './logs/https-combined.log',
      time: true,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: 'lyra-proxy',
      script: 'scripts/proxy-server.mjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      node_args: '--max-old-space-size=300',
      env: {
        NODE_ENV: 'production',
        PROXY_PORT: 8080,
        NODE_OPTIONS: '--max-old-space-size=300',
      },
      error_file: './logs/proxy-error.log',
      out_file: './logs/proxy-out.log',
      log_file: './logs/proxy-combined.log',
      time: true,
      kill_timeout: 3000,
      listen_timeout: 5000,
    },
  ],
};
